name: Generate Snake Game

on:
  push: # このアクションはpushイベントでトリガーされます。必要に応じて変更してください。

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: generate-snake-game-from-github-contribution-grid
      uses: Platane/snk@v3.0.0

